### ISSUE TITLE
[Bug]: RuntimeError: Windows not yet supported for torch.compile

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [openvinotoolkit/stable-diffusion-webui#29]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I got this error in the cmd :  RuntimeError: Windows not yet supported for torch.compile

Or more precisely :  File "C:\Users\myname\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\_dynamo\eval_frame.py", line 375, in check_if_dynamo_supported
        raise RuntimeError("Windows not yet supported for torch.compile")
    RuntimeError: Windows not yet supported for torch.compile

### Steps to reproduce the problem

1. Try to run it with an A770

### What should have happened?

To work

### Version or Commit where the problem happens

Idk? Latest?

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

Other GPUs

### Cross attention optimization

Automatic

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
no
```

### List of extensions

no

### Console logs

```Shell
*** Error completing request
*** Arguments: ('task(fkmbimsh3gdm89b)', 'DQDESDSECF', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 0, '', '', [], <gradio.routes.Request object at 0x000001A4AC435DB0>, 1, 'None', 'GPU', True, 'Euler a', True, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0) {}
    Traceback (most recent call last):
      File "C:\Users\myname\stable-diffusion-webui\modules\call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\myname\stable-diffusion-webui\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "C:\Users\myname\stable-diffusion-webui\modules\txt2img.py", line 59, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *args)
      File "C:\Users\myname\stable-diffusion-webui\modules\scripts.py", line 501, in run
        processed = script.run(p, *script_args)
      File "C:\Users\myname\stable-diffusion-webui\scripts\openvino_accelerate.py", line 774, in run
        processed = process_images_openvino(p, model_config, p.sampler_name, enable_caching, openvino_device, mode)
      File "C:\Users\myname\stable-diffusion-webui\scripts\openvino_accelerate.py", line 523, in process_images_openvino
        shared.sd_diffusers_model = get_diffusers_sd_model(model_config, sampler_name, enable_caching, openvino_device, mode)
      File "C:\Users\myname\stable-diffusion-webui\scripts\openvino_accelerate.py", line 341, in get_diffusers_sd_model
        sd_model.unet = torch.compile(sd_model.unet, backend="openvino_fx")
      File "C:\Users\myname\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\__init__.py", line 1441, in compile
        return torch._dynamo.optimize(backend=backend, nopython=fullgraph, dynamic=dynamic, disable=disable)(model)
      File "C:\Users\myname\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\_dynamo\eval_frame.py", line 413, in optimize
        check_if_dynamo_supported()
      File "C:\Users\myname\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\_dynamo\eval_frame.py", line 375, in check_if_dynamo_supported
        raise RuntimeError("Windows not yet supported for torch.compile")
    RuntimeError: Windows not yet supported for torch.compile
```

### Additional information

I am using an A770 16GB. This works only with CPU, but EXTREMELY slow

**Comment by qiacheng** [comment]
did you run torch-install.bat after first-time-runner.bat finishes installing required dependencies? torch-install.bat will modify the dev torch package to support torch.compile on windows

**Comment by TheWonderfulTartiflette** [comment]
I'm currently having [another issue](https://github.com/openvinotoolkit/stable-diffusion-webui/issues/30) that prevents me from checking this, I'll tell you as soon as I fixed this another issue

**Comment by TheWonderfulTartiflette** [comment]
@qiacheng It works now, but from what I remember I was having this error when I was at the first-time-runner.bat stage, and torch-install.bat comes after. But hey, this works now :D
